#!/usr/bin/python


COURSES = [
    #'advanced-linux-the-linux-kernel',
	#'ruby-on-rails-5-essential-training',
	#'vue-js-building-an-interface',
	#'vue-js-for-web-designers',
    #'learning-vue-js-3',

    # 'android-development-essential-training-create-your-first-app',
    # 'android-studio-essential-training-2016',
    # 'android-app-development-communicating-with-the-user',
    # 'android-development-essential-training-local-data-storage',
    # 'building-flexible-android-apps-with-the-fragments-api',
    # 'android-app-development-animations-and-transitions',
    # 'building-a-note-taking-app-for-android',
    # 'android-app-development-restful-web-services',
    # 'android-app-development-unit-testing',
    # 'android-development-essential-training-distributing-apps',

    # 'programming-foundations-real-world-examples',
    # 'python-advanced-design-patterns',
    # 'advanced-python',
    # 'python-design-patterns',
    # 'code-clinic-python-2',
    #'learning-python-generators',
    # 'python-gui-development-with-tkinter',
    # 'learning-the-python-3-standard-library',
    # 'learning-python-2',


    # 'learning-java-by-example',
    # 'learning-java-9-modularity',
    # 'advanced-java-programming',
    # 'java-database-integration-with-jdbc',
    # 'java-for-data-scientists-essential-training',
    # 'nail-your-java-interview',
    # 'code-clinic-java-2',
    # 'java-design-patterns-creational',
    # 'java-essential-training-syntax-and-structure',
    # 'learning-java-3',
    # 'c-plus-plus-essential-training',
    # 'code-clinic-c-plus-plus',
    # 'c-plus-plus-move-semantics',
    # 'c-plus-plus-building-a-string-library',
    # 'c-plus-plus-design-patterns-creational',
    # 'c-plus-plus-standard-template-library',
    # 'c-plus-plus-smart-pointers',
    # 'c-plus-plus-essential-training-for-career-changers',
    #'ruby-essential-training',
    #'react-js-essential-training',
    # 'learning-graphql',
    # 'learning-ecmascript-6',
    #'learning-full-stack-javascript-development-mongodb-node-and-react',
    # 'building-an-app-with-react-js-and-meteorjs',
    # 'react-server-side-rendering',
    # 'react-react-router',
    # 'react-components-context-and-accessibility',
    # 'webpack-for-react-applications',
    # 'react-recipes',
    # 'react-testing-and-debugging',
    # 'react-securing-applications',
    # 'react-native-building-mobile-apps-3',
    #'building-and-deploying-a-full-stack-react-application',
    #'the-dom-in-javascript-jquery-angularjs-and-react',
    #'bootstrap-4-essential-training',
    #'http-2-developing-for-performance',
    #'linux-foundation-cert-prep-service-configuration-ubuntu',
    #'programming-foundations-code-efficiency',
    #'web-programming-foundations',
    #'programming-foundations-design-patterns',
    #'visual-basic-essential-training'
    # 'programming-foundations-databases',
    # 'programming-foundations-data-structures',
    # 'programming-foundations-test-driven-development',
    # 'programming-foundations-object-oriented-design',
    # 'java-essential-training-objects-and-apis',
    # 'kotlin-essential-training'
    # 'learning-php-2',
    # 'php-essential-training-2',
    # 'node-js-essential-training'
    #done'installing-apache-mysql-and-php-2'
    #done'learning-bash-scripting'
    #'charlene-li-on-digital-leadership',
    # 'fred-kofman-on-managing-conflict',
    # 'reid-hoffman-and-chris-yeh-on-creating-an-alliance-with-employees',
    # 'bill-george-on-self-awareness-authenticity-and-leadership',
    # 'sallie-krawcheck-on-risk-taking',
    # 'betsy-corcoran-on-choosing-the-right-technology-for-your-school',
    # 'betty-liu-on-career-success',
    # 'j-t-o-donnell-on-making-recruiters-come-to-you',
    # 'gary-hamel-on-busting-bureaucracy',
    # 'shane-snow-on-storytelling',
    # 'john-maeda-on-design-business-and-inclusion',
    # 'esther-dyson-on-cultivating-health-at-scale',
    # 'influencer-interview-oprah-winfrey'
]
